services:

  backend:
    image: ghcr.io/rafakka/mexe-backend:${MEXE_VERSION:?MEXE_VERSION must be set}

  frontend:
    image: ghcr.io/rafakka/mexe-frontend:${MEXE_VERSION:?MEXE_VERSION must be set}
    ports:
      - "8080:80"
