
export const STARTUP_DURATION = 1000;

export const SYNCHRONIZING_DURATION =1000;

export const PROCESSING_DURATION = 1000;

export const AXIS_REVEAL_DURATION = 1000;

export const AXIS_ROTATION_TIME = 8000;

export const STABILIZATION_DURATION = 5000;

export const RESULT_DURATION = 1000;

export const RESET_DURATION = 1200;
